### PR TITLE
add macros to ease the AXI signals use

### PR DESCRIPTION
**Pull request by JDLopes**

### CODE REVIEW

**Comment by jjts** [comment]
Please list the new macros and what they do as an answer to this comment

**Comment by JDLopes** [comment]
> Please list the new macros and what they do as an answer to this comment

These are the main macros, but there are a few more, as explained below.

For ports:
AXI4_M_IF_CORE(CORE) - it declares all the input and output signals with the prefix "CORE_", for the master;
AXI4_S_IF_CORE(CORE) - it declares all the input and output signals with the prefix "CORE_", for the slave.

There are a few more variants for the same purpose (without the prefix "CORE_", for instance) and for helping to construct the other macros.

The user has the choice to use these macros at the end or at the beginning of the ports declaration of a module, by putting a comma at the end or not (so there is no obligation to use the macros at the beginning of the ports list).

For connections:
AXI4_M_IF_CON_CORE2CORE(CORE_INT, CORE_EXT) - it declares all the input and output signals with the prefix "CORE_INT_" connected to all the input and output signals with the prefix "CORE_EXT_", for the master;
AXI4_S_IF_CON_CORE2CORE(CORE_INT, CORE_EXT) - it declares all the input and output signals with the prefix "CORE_INT_" connected to all the input and output signals with the prefix "CORE_EXT_", for the slave;
AXI4_M2S_IF_CON_CORE2CORE(CORE_INT, CORE_EXT) - it declares all the input and output master signals with the prefix "CORE_INT_" connected to all the input and output slave signals with the prefix "CORE_EXT_";
AXI4_S2M_IF_CON_CORE2CORE(CORE_INT, CORE_EXT) - it declares all the input and output slave signals with the prefix "CORE_INT_" connected to all the input and output master signals with the prefix "CORE_EXT_";
AXI4_2M_IF_CON_CORE2CORE(CORE_INT, CORE_EXT) - it declares all the input and output signals with the prefix "CORE_INT_" (with no reference to master nor slave) connected to all the input and output master signals with the prefix "CORE_EXT_";
AXI4_2S_IF_CON_CORE2CORE(CORE_INT, CORE_EXT) - it declares all the input and output signals with the prefix "CORE_INT_" (with no reference to master nor slave) connected to all the input and output slave signals with the prefix "CORE_EXT_";

Here there are also a few more variants for the same purpose and for helping to construct the other macros.

The user has the choice to use these macros at the end or at the beginning of the signals connection of a module, by putting a comma at the end or not (so there is no obligation to use the macros at the beginning of the signals list).

For signals declaration:
AXI4_M_IF_W_CORE(CORE) - it declares all the signals as wires with the prefix "CORE_", for the master (so the user can connect 2 cores that use the AXI4 protocol);
AXI4_S_IF_W_CORE(CORE) - it declares all the signals as wires with the prefix "CORE_", for the slave (so the user can connect 2 cores that use the AXI4 protocol);

As happens with the macros for ports and connections, there are a few more variants for the same purpose and for helping to construct the other macros.

These macros have the semicolon implicit.

**Comment by jjts** [comment]
The first two:
AXI4_M_IF_PORT(PREFIX) - declares all AXI4 master ports with the prefix "PREFIX_".
AXI4_S_IF_CORE(PREFIX) - declares all AXI4 slave ports with the prefix "PREFIX_".

the others I don't understand what they do by the name. I would need to read the code

**Comment by JDLopes** [comment]
> The first two:
> AXI4_M_IF_PORT(PREFIX) - declares all AXI4 master ports with the prefix "PREFIX_".
> AXI4_S_IF_CORE(PREFIX) - declares all AXI4 slave ports with the prefix "PREFIX_".
> 
> the others I don't understand what they do by the name. I would need to read the code

These macros are all about AXI4-full interface (AXI4_IF). Some of those, for the master (AXI4_M_IF), the others for the slave (AXI4_S_IF). Later on, more macros for the AXI4-lite, or for the AXI4-stream interfaces can be added.

The first ones (the ones for the ports) have the name AXI4_X_IF* (where the X can be M or S), and are meant to be used in the declaration of ports of a module.

The second ones (the ones for connections) have the name AXI4_X_IF_CON* (where the X can be M, S, M2S, S2M, 2M, or 2S), and are meant to be used in the connections between modules. For example:

core1 core1 (
                     .core_int1_signal(core_ext1_signal)
);

core2 core2 (
                     .core_int2_signal(core_ext2_signal)
);

Instead of write ".signal(signal)" for all the AXI signals, the user only need to use one of these macros. CORE_INT and CORE_EXT are used to add a prefix to distinguish both cores (the one being instantiated and the one where the first is being instantiated).

The third and last ones (the ones for the signals declaration) have the name AXI4_X_IF_W (where the X can be M or S), and are meant to be used in the wire signals declaration. Using the same example above, "wire [width-1:0] signal;" must be added before the cores instantiation.

The macros name may be improved, but these macros are very useful to use cores with AXI4-full interface (in terms of wiring, the connection between modules and ports declaration).

**Comment by jjts** [comment]
Instead of AXI4_M_IF_CON_CORE2CORE(CORE_INT, CORE_EXT) 

AXI4_M_IF_PORTMAP(INSTANCE_PORT_PREFIX, WIRE_PREFIX)

**Comment by JDLopes** [comment]
> Instead of AXI4_M_IF_CON_CORE2CORE(CORE_INT, CORE_EXT)
> 
> AXI4_M_IF_PORTMAP(INSTANCE_PORT_PREFIX, WIRE_PREFIX)

Macros renamed

**Pull request closed without merging**
